"""create users table

Revision ID: 099d4f286fde
Revises: 
Create Date: 2025-10-21 14:28:02.329497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '099d4f286fde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_timestamp'))

    op.drop_table('sensor_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sensor_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('value', mysql.FLOAT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('device_id', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_timestamp'), ['timestamp'], unique=False)

    op.drop_table('user')
    # ### end Alembic commands ###
