"""create aktuator table

Revision ID: 13eef9127d5f
Revises: c8d82710ce27
Create Date: 2025-10-29 14:31:25.569535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13eef9127d5f'
down_revision = 'c8d82710ce27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aktuator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akt_name', sa.Enum('water', 'ph', 'lamp'), nullable=False),
    sa.Column('runtime', sa.TIMESTAMP(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aktuator')
    # ### end Alembic commands ###
