"""create sensor & user table

Revision ID: 14d61fd6c80a
Revises: 188fb2ec7d04
Create Date: 2025-10-28 14:46:20.683091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d61fd6c80a'
down_revision = '188fb2ec7d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.Enum('dht', 'ldr', 'ph', 'ec', 'ultrasonic'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor')
    # ### end Alembic commands ###
