"""update user table

Revision ID: 85c08ecc99d8
Revises: 099d4f286fde
Create Date: 2025-10-23 10:18:52.754458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c08ecc99d8'
down_revision = '099d4f286fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('user', 'admin'), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'inactive'), nullable=False))
        batch_op.add_column(sa.Column('timestammp', sa.TIMESTAMP(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timestammp')
        batch_op.drop_column('status')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
