"""update user table

Revision ID: 96ddfcbf4093
Revises: 85c08ecc99d8
Create Date: 2025-10-23 10:54:28.709333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96ddfcbf4093'
down_revision = '85c08ecc99d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.TIMESTAMP(), nullable=False))
        batch_op.drop_column('timestammp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestammp', mysql.TIMESTAMP(), nullable=False))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
