"""create update table

Revision ID: c8d82710ce27
Revises: 14d61fd6c80a
Create Date: 2025-10-29 11:43:17.192477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d82710ce27'
down_revision = '14d61fd6c80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('value'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('value'), ['value'], unique=True)

    # ### end Alembic commands ###
